# tasks for Red Hat Familly
---

- name: Change SELinux state
  selinux:
    policy: targeted
    state: permissive
  when: ansible_selinux.status == 'enabled'

- name: Repository installation
  yum:
    name: "{{ xtradb_repo_baseurl }}"
    state: present

- name: Replace Percona Release Repo file
  template:
    dest: /etc/yum.repos.d/percona-original-release.repo
    group: root
    owner: root
    mode: 0644
    src: percona-original-release.repo

- name: Yum Clean Cache
  command: yum clean all
  args:
    warn: no

- name: Install percona-xtradb-packages
  yum:
    name: "{{ xtradb_packages }}"
    state: present

...
