---

- name: Install ProxySQL from repository
  yum:
    name: "{{ proxysql_pkgs }}"
    state: present
    update_cache: "{{ omit if ((ansible_pkg_mgr == 'dnf') and (ansible_version is version('2.7', '<'))) else 'yes' }}"
  delay: 10
  register: result
  retries: 3
  until: result is succeeded
  when:
    - proxysql_use_percona_repo
