# roles/ansible-percona-cluster/defaults/main.yml
---

# Data directory
xtradb_datadir: /var/lib/mysql

# Defines the user used
xtradb_mysql_user: mysql

# setup cookie
xtradb_configured: "{{ xtradb_confdir }}/_configured"

# secure cookie
xtradb_secured: "{{ xtradb_confdir }}/_secured"

# password changed cookie
xtradb_password_changed: "{{ xtradb_confdir }}/_password_changed"

#ansible_host Defnes the root user
xtradb_root_user: root

# Defines the root password
xtradb_root_password: root

# Define Ansible group in which the nodes exist to be part of the cluster
# this is percona nodes group in inventory
xtradb_nodes_group: key_percona

xtradb_wsrep_provider: /usr/lib64/galera3/libgalera_smm.so

# Define the node pool
xtradb_wsrep_cluster_address: "gcomm://{{ groups[xtradb_nodes_group] | map('extract', hostvars, ['ansible_' ~ xtradb_bind_interface, 'ipv4', 'address']) | join(',') }}"

# Defines the which node should be considered the master in the cluster
# Used to bootstrap cluster
xtradb_master_node: "{{ hostvars[ groups[xtradb_nodes_group][0] ].ansible_default_ipv4.address }}"

# Defines the version
xtradb_version: "57"

# Define the package
xtradb_release: latest

# Defines the service systmd
xtradb_service: mysql

# Defines the network interfaces used
xtradb_bind_interface: eth0

# Defines the network address used
xtradb_bind_address: "{{ hostvars[inventory_hostname]['ansible_' + xtradb_bind_interface]['ipv4']['address'] }}"

# Defines the sst user
xtradb_sst_user: sstuser

# Defines the sst password
xtradb_sst_password: sstpassword

# Defines the cluster name: it can be defined in Azure resources. Below is an example
xtradb_cluster_name: pxc-cluster

xtradb_swappiness: 0

# Defines users to create
# List of dicts specifing the users to be added.
# Users are defined with a dict containing fields `name:`, `password:`, `priv:`, and, optionally, `host:`.
# The password is in plain text and `priv:` specifies the privileges for this user as described in the [Ansible documentation](http://docs.ansible.com/mysql_user_module.html).
#
# An example:
#
# xtradb_users:
#   - name: 1
#     password: 1_DBPASS
#     priv: '1.*:SUPER'
#
#   - name: 2
#     password: 2_DBPASS
#     priv: 'mydb.*:ALL'
#     host: '192.168.1.%'
xtradb_users:
   - name: user1
     password: user1password
     priv: '*.*:ALL'
     host: '%'
   - name: proxysql-mysql-user
     password: user2password
     priv: '*.*:ALL'
     host: '%'

   - name: proxysql-monitor-user
     password: user3password
     priv: '*.*:USAGE'
     host: '%'


# Defines databases to create.
# List of names of the databases to be added
# Databases are defined with a dict containing
# the fields `name:` (required), and `init_script:` (optional).
# The init script is a SQL file that is executed when the database
# is created to initialise tables and populate it with values.
# An Example:

# xtradb_databases:
#  - name: _db
#  - name: mydb
#    init_script: files/init_mydb.sql

xtradb_databases:
  - name: your_database_name


xtradb_binlog_format: "ROW"
xtradb_character_set_server: "utf8"
xtradb_collation_server: "utf8_general_ci"
xtradb_default_storage_engine: "InnoDB"
xtradb_innodb_autoinc_lock_mode: 2
xtradb_innodb_buffer_pool_instances: ""
xtradb_innodb_buffer_pool_size: ""
xtradb_innodb_file_format: ""
xtradb_innodb_file_format_check: ""
xtradb_innodb_file_per_table: ""
xtradb_innodb_flush_log_at_trx_commit: ""
xtradb_innodb_log_buffer_size: ""
xtradb_innodb_log_file_size: ""
xtradb_innodb_strict_mode: "on"
xtradb_join_buffer_size: ""
xtradb_log_warnings: ""
xtradb_long_query_time: ""
xtradb_max_allowed_packet: ""
xtradb_max_connections: "4096"
xtradb_max_heap_table_size: ""
xtradb_max_user_connections: ""
xtradb_pxc_strict_mode: "PERMISSIVE"
xtradb_query_cache_size: ""
xtradb_read_buffer_size: ""
xtradb_read_rnd_buffer_size: ""
xtradb_skip_name_resolve: "1"
xtradb_slow_query_log: "0"
xtradb_socket: ""
xtradb_sort_buffer_size: ""
xtradb_table_definition_cache: ""
xtradb_table_open_cache: ""
xtradb_table_open_cache_instances: ""
xtradb_tmp_table_size: ""

...
